### ISSUE TITLE
not found weight file

### ISSUE THREAD

**Issue by Cguanqin** [google/gemma_pytorch#31] opened 2024-03-01 03:33 UTC
Build the image according to the dockerfile file, then run the container. Error: IsADirectoryError: [Errno 21] Is a directory: '/tmp/ckpt', it should be that there is no weight file in the directory '/tmp/ckpt'. Did not a weight file be generated when building the image? How to solve this problem?

**Comment by Cguanqin** [comment] 2024-03-01 03:41
[root@iZwz9fjpavyfd2ybhfxx1lZ gemma_pytorch]# docker run -t --rm \
>     -v /tmp/ckpt:/tmp/ckpt \
>     gemma:pytorch \
>     python scripts/run.py \
>     --ckpt=/tmp/ckpt \
>     --variant="2b" \
>     --prompt="The meaning of life is"
Traceback (most recent call last):
  File "/workspace/gemma/scripts/run.py", line 79, in <module>
    main(args)
  File "/workspace/gemma/scripts/run.py", line 48, in main
    model.load_weights(args.ckpt)
  File "/workspace/gemma/gemma/model.py", line 562, in load_weights
    torch.load(
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/tmp/ckpt'

**Comment by TAOSHss** [comment] 2024-04-25 11:32
> Hi @Cguanqin, have you downloaded the checkpoint from Kaggle or HuggingFace Hub before running the docker?
> 
> You can follow the instruction here to get the checkpoint. https://www.kaggle.com/models/google/gemma/frameworks/pyTorch

I have confirmed that I have downloaded the model, but I am still encountering this error regardless of whether I specify the path where the model was downloaded or the path to the model file itself.

**Comment by Gopi-Uppari** [comment] 2024-09-24 05:49
Hi @Cguanqin,

Could you please confirm if this issue is resolved for you with the above comment ? Please feel free to close the issue if it is resolved ?

Thank you.

**Comment by Gopi-Uppari** [comment] 2024-10-07 05:16
Hi @Cguanqin,

Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. 

Thank you!

**Closed by Gopi-Uppari** 2024-10-07 05:16 UTC
Labels: type:support, stat:awaiting response
